# Generated by Django 5.0.6 on 2025-07-02 01:06

import datetime
import django.db.models.deletion
import modelcluster.contrib.taggit
import wagtail.fields
import wagtailmarkdown.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puput', '0008_alter_tagentrypage_tag'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('trips', '0011_alter_triptag_name'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='body')),
                ('markdown_body', wagtailmarkdown.fields.MarkdownField(blank=True, null=True, verbose_name='body (Markdown)')),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name='Post date')),
                ('excerpt', wagtail.fields.RichTextField(blank=True, help_text='Entry excerpt to be displayed on entries list. If this field is not filled, a truncate version of body text will be used.', verbose_name='excerpt')),
                ('num_comments', models.IntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_reports', to=settings.AUTH_USER_MODEL)),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Header image')),
                ('tags', modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='puput.TagEntryPage', to='taggit.Tag', verbose_name='Tags')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_reports', to='trips.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripReportCategoryEntryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puput.category')),
                ('tripreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripreports.tripreport')),
            ],
            options={
                'unique_together': {('tripreport', 'category')},
            },
        ),
        migrations.AddField(
            model_name='tripreport',
            name='categories',
            field=models.ManyToManyField(blank=True, through='tripreports.TripReportCategoryEntryPage', to='puput.category'),
        ),
    ]
