# Generated by Django 5.2.8 on 2026-01-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_alter_tripsignup_trip_alter_tripsignup_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
