# Generated by Django 5.2.8 on 2025-12-05 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_profile_emergency_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=datetime.date(2025, 12, 5)),
        ),
    ]
