# Generated by Django 5.2.8 on 2025-12-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inreach_address',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
