# Generated by Django 5.2.8 on 2026-01-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0031_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
