# Generated by Django 5.2.8 on 2025-12-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubc_voc_website', '0002_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='fake@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
