# Generated by Django 5.2.8 on 2026-01-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubc_voc_website', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
