# Generated by Django 5.2.10 on 2026-01-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripreports', '0002_tripreportcategory_tripreport_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='old_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
