# Generated by Django 5.2.10 on 2026-01-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripreports', '0004_tripreport_legacy_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
