# Generated by Django 5.2.10 on 2026-01-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripreports', '0006_alter_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreport',
            name='body',
            field=models.TextField(),
        ),
    ]
