# Generated by Django 5.2.8 on 2025-12-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0005_remove_bookrental_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrental',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrental',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gearrental',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gearrental',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
